# Copyright bysssss Corp. All Rights Reserved.

version: '2'

networks:
  basic:

services:
  orderer.fabtest13.com:
    container_name: orderer.fabtest13.com
    image: hyperledger/fabric-orderer:1.3.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP13
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./configtx/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/fabtest13.com/orderers/orderer.fabtest13.com/:/etc/hyperledger/crypto-config/orderer
        - ./crypto-config/peerOrganizations/samsung1.fabtest13.com/peers/peer0.samsung1.fabtest13.com/:/etc/hyperledger/crypto-config/samsung1
        - ./crypto-config/peerOrganizations/hyundai2.fabtest13.com/peers/peer0.hyundai2.fabtest13.com/:/etc/hyperledger/crypto-config/hyundai2
    networks:
      - basic

  peer0.samsung1.fabtest13.com:
    container_name: peer0.samsung1.fabtest13.com
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.samsung1.fabtest13.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=SamsungMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/samsung1/msp
      - CORE_PEER_ADDRESS=peer0.samsung1.fabtest13.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./configtx/:/etc/hyperledger/configtx
	- ./crypto-config/peerOrganizations/samsung1.fabtest13.com/peers/peer0.samsung1.fabtest13.com/:/etc/hyperledger/crypto-config/samsung1
        - ./crypto-config/peerOrganizations/samsung1.fabtest13.com/users:/etc/hyperledger/crypto-config/samsungusers
    depends_on:
      - orderer.fabtest13.com
      - couchdb1
    networks:
      - basic

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic
