# Copyright bysssss Corp. All Rights Reserved.

version: '2'

networks:
  basic:

services:
  #ca.fabtest13.com:
    #container_name: ca.fabtest13.com
    #image: hyperledger/fabric-ca:1.3.0
    #environment:
      #- FABRIC_CA_HOME=/etc/hyperledger/fabric-ca
      #- FABRIC_CA_SERVER_CA_NAME=ca.fabtest13.com
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/crypto-config/samsung1/ca/ca.samsung1.fabtest13.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/crypto-config/samsung1/ca/7877a1f48c8a74c76e10870ce01113044d74bdd38b3437596e2dc60feef9aa1a_sk
    #command: sh -c 'fabric-ca-server start -b admin:adminpw'
    #ports:
      #- 7054:7054
    #volumes:
      #- ./crypto-config/peerOrganizations/samsung1.fabtest13.com/ca/:/etc/hyperledger/crypto-config/samsung1/ca
      #- ./crypto-config/peerOrganizations/hyundai2.fabtest13.com/ca/:/etc/hyperledger/crypto-config/hyundai2/ca
    #networks:
      #- basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_LOCALMSPID=SamsungMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/samsung1/users/Admin@samsung1.fabtest13.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/samsung1.fabtest13.com/users/:/etc/hyperledger/crypto-config/samsung1/users
    networks:
        - basic
