NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.samsung1.fabtest13.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.samsung1.fabtest13.com-cert.pem
    OrganizationalUnitIdentifier: peer
